version: '3.8'

services:
  mongodb:
    build:
      context: ./docker/mongod
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    command: ["--bind_ip_all"]

  nodeapp:
    build:
      context: ./arduino
    container_name: node-arduino
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sensordb
    volumes:
      - ./arduino:/usr/src/app
    working_dir: /usr/src/app
    command: node app.js
    depends_on:
      - mongodb
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
