apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: your-nodeapp-image:latest  # 나중에 docker image build & push 후 업데이트
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017/sensordb
          volumeMounts:
            - name: node-volume
              mountPath: /usr/src/app
      volumes:
        - name: node-volume
          emptyDir: {}  # 또는 실제 파일 매핑이 필요하면 PVC 사용
